@purpuraMain_HostAddress = http://localhost:5188



/// USER TESTS

### Enviar un correo elecrónico para recuperar la contraseña
POST  {{purpuraMain_HostAddress}}/user/sendRecoveryMail?email=mario@gmail.com
Accept: application/json



### Obtener un usuario por su id
GET {{purpuraMain_HostAddress}}/user/15f10770-1beb-4476-8e8e-303a78a73266
Accept: application/json


### Obtener un usuario por su email
GET {{purpuraMain_HostAddress}}/user/getByEmail/mario@gmail.com
Accept: application/json


### Crear Un Usuario
POST {{purpuraMain_HostAddress}}/user
Accept: application/json
Content-Type: application/json

{
  "email": "vargasloaizacristian@gmail.com",
  "password": "Password@432",
  "firstname": "Cristian David",
  "surname": "Vargas Loaiza",
  "country": 1
}

### Actualizar Un Usuario
PUT {{purpuraMain_HostAddress}}/user
Accept: application/json
Content-Type: application/json

{
  "id": "6f4c8c96-b10f-4a12-80cd-668d70c5d573",
  "email": "maria@gmail.com",
  "password": "password456",
  "name": "Mario Angel García",
  "phone": "3003893442",
  "country": 2
}

### Verificar la cuenta de un usuario
PUT {{purpuraMain_HostAddress}}/user/verifyAccount
Accept: application/json
Content-Type: application/json

{
  "email": "mario@gmail.com",
  "code": "1704"
}


### Cambiar la contraseña de un usuario
PUT {{purpuraMain_HostAddress}}/user/changePassword
Accept: application/json
Content-Type: application/json

{
  "email": "mario@gmail.com",
  "code": "4067",
  "password": "Password-4567@"
}


### Eliminar un usuario
DELETE {{purpuraMain_HostAddress}}/user/ieopskd2p12k2
Accept: application/json




// PLAYLIST TESTS

### Obtener una playlist con sus canciones
GET {{purpuraMain_HostAddress}}/playlist/be4f4676-4297-4f2a-bdaa-57227306c87c
Accept: application/json

### buscar una o varias pleylist por su nombre
GET {{purpuraMain_HostAddress}}/playlist/search/hip-
Accept: application/json

### Añadir una canción a una playlist (Debe ser del usuario que la creó)
PUT {{purpuraMain_HostAddress}}/playlist/addSong
Accept: application/json
Content-Type: application/json

{
  "playlistId": "1",
  "songId": "1"
}

### Eliminar una canción de una playlist (Debe ser del usuario que la creó)
PUT {{purpuraMain_HostAddress}}/playlist/removeSong
Accept: application/json
Content-Type: application/json

{
  "playlistId": "1",
  "songId": "1"
}

### Cambiar la visibilidad de una playlist (Debe ser del usuario que la creó)
PUT {{purpuraMain_HostAddress}}/playlist/changePrivacy
Accept: application/json
Content-Type: application/json

{
  "id": "be4f4676-4297-4f2a-bdaa-57227306c87c",
  "userId": "6f4c8c96-b10f-4a12-80cd-668d70c5d573"
}

### Obtener las playlists de un usuario 
GET {{purpuraMain_HostAddress}}/playlist/getPlaylists/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImIwZTI1Y2IxLWQ3NjQtNGI1Ny1hNmJmLTcyODg2Nzk0NTc3MCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1hcmlhQGdtYWlsLmNvbSIsImV4cCI6MTczNzU5NzQ3MiwiaXNzIjoiUHVycHVyYU11c2ljIiwiYXVkIjoiUHVycHVyYU11c2ljIn0.ZVaF042x6lFjdDgaOLl1jsp9z8LymWKzIGnJj83fcsM
Accept: application/json


### Crear una playlist
POST {{purpuraMain_HostAddress}}/playlist
Accept: application/json
Content-Type: application/json

{
  "name": "I love harry styles",
  "userId": "b0e25cb1-d764-4b57-a6bf-728867945770"
}
### Actualizar una playlist (Debe ser del usuario que la creó)
PUT {{purpuraMain_HostAddress}}/playlist 
Accept: application/json
Content-Type: application/json

{
  "id": "8d92e7f9-6524-42af-b6e8-babce6df92d2",
  "name": "Vice city vibes",
  "description": "60s 70s and 80s songs that make you feel like you are in Vice city"

}
### Eliminar una playlist
DELETE {{purpuraMain_HostAddress}}/playlist/
Accept: application/json
Content-Type: application/json

{
  "id": "348d314d-483c-455c-a5fe-d1eaa59ae2fd",
  "userId": "6f4c8c96-b10f-4a12-80cd-668d70c5d573"
}


### Obtener canciones por nombre, artista o album
GET {{purpuraMain_HostAddress}}/song/search/songs/ifeelitcoming
Accept: application/json



### METODOS DE LIBRERIA


### Obtener canciones por nombre, artista o album
GET {{purpuraMain_HostAddress}}/library/6f4c8c96-b10f-4a12-80cd-668d70c5d573
Accept: application/json



### Métodos de Género

### Obtener las canciones mas escuchadas por genero
GET {{purpuraMain_HostAddress}}/genre/getTopSongs/1
Accept: application/json

### Obtener todos los generos
GET {{purpuraMain_HostAddress}}/genre/getAll
Accept: application/json
### Obtener todos los generos

GET {{purpuraMain_HostAddress}}/genre/getGenre/0c1e6e02-b50b-427e-86fc-552b3c7fb745
Accept: application/json

### Crear un genero
POST {{purpuraMain_HostAddress}}/genre
Accept: application/json
Content-Type: application/json

{
  "name":"Pop",
  "Description":"Pupular Songs",
  "Color":"#2E5DF0"
}

### Actualizar un genero
PUT {{purpuraMain_HostAddress}}/genre
Accept: application/json
Content-Type: application/json

{
  "id":"0c1e6e02-b50b-427e-86fc-552b3c7fb745",
  "name":"Pop",
  "Description":"Catchy, commercial, and memorable music with simple harmonies.",
  "Color":"#2E5DF0"
}

### Eliminar un genero
GET {{purpuraMain_HostAddress}}/library/6f4c8c96-b10f-4a12-80cd-668d70c5d573
Accept: application/json


### Obtener un album
GET {{purpuraMain_HostAddress}}/album/getAlbumByInput/gg
Accept: application/json

### Obtener un album
GET {{purpuraMain_HostAddress}}/album/getAlbum/2e465b8d-aa39-4a8e-85a5-ea4daac845e0
Accept: application/json

### Obtener todos los albumes
GET {{purpuraMain_HostAddress}}/album/getAlbums?offset=0&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMGUyNWNiMS1kNzY0LTRiNTctYTZiZi03Mjg4Njc5NDU3NzAiLCJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImV4cCI6MTczNzU5MzM3NywiaXNzIjoiUHVycHVyYU11c2ljIiwiYXVkIjoiUHVycHVyYU11c2ljIn0.QjWzpUARrG9FpnrXDnEth14ihI9yztYd_VvoKeeQb6M
Accept: application/json




### Obtener un artista
GET {{purpuraMain_HostAddress}}/artist/searchArtists?name=the&offset=0&limit=10
Accept: application/json

### Obtener un artista
GET {{purpuraMain_HostAddress}}/artist/getArtists?offset=0&limit=10
Accept: application/json


### Obtener un artista
GET {{purpuraMain_HostAddress}}/artist/getArtistProfile/99e516b1-592d-4c72-afb9-8a060821844d
Accept: application/json



### Obtener todas las canciones 
GET {{purpuraMain_HostAddress}}/song/getSongs?offset=0&limit=10
### Obtener todas las canciones 
GET {{purpuraMain_HostAddress}}/song/getSong/39a79345-e31b-46e7-8c71-15bcabec3a4a


### Auth tests 
POST {{purpuraMain_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "vargasloaizacristian@gmail.com",
  "password": "Cris-2004"
}
### refreshToken
PUT {{purpuraMain_HostAddress}}/api/auth/refresh/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlkMjhiNzgxLWY0NDItNDNjMC1iYzBlLWRlYmYwYTA2YjlhMiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvc2VyaWFsbnVtYmVyIjoiMTlhNGM0NTUtMzdiOS00YTE5LTllYmUtOTZlNDNkZGZjNDljIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidmFyZ2FzbG9haXphY3Jpc3RpYW5AZ21haWwuY29tIiwiZXhwIjoxNzM4MjgzMjM2LCJpc3MiOiJQdXJwdXJhTXVzaWMiLCJhdWQiOiJQdXJwdXJhTXVzaWMifQ.HD2AyqxMnSmYz2GDntqkAiv2-oq0vvcYMXD545MFJAU
Content-Type: application/json
### refreshToken


GET {{purpuraMain_HostAddress}}/country/getAll
Content-Type: application/json

###
PUT {{purpuraMain_HostAddress}}/api/auth/checkToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlkMjhiNzgxLWY0NDItNDNjMC1iYzBlLWRlYmYwYTA2YjlhMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InZhcmdhc2xvYWl6YWNyaXN0aWFuQGdtYWlsLmNvbSIsImV4cCI6MTczNzg1NTkwNCwiaXNzIjoiUHVycHVyYU11c2ljIiwiYXVkIjoiUHVycHVyYU11c2ljIn0.I_jH72MghAAiU2bdvgwz_Hig9Tqe7PzUe00TlxHd3YU
Content-Type: application/json
### refreshToken

